#!/bin/bash

#
# ./gxbase-setup
#   
#   setup program for gxbase, and, the script called by gxbase when not sourced
# 
# Author:
#    Gabriel Thomas Sharp <osirisgothra@hotmail.com>  
# 
# Copyright (C)2013 Paradisim Enterprises, LLC 
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# This file was created 
# For more support, visit our homepage: http://paradisim.tk
# Report any bugs to <bugs@paradisim.tk> or visit our FAQ on our website.
#



# program
function _gen.dlg()
{
	RESULT_FILE=$(tempfile --suffix=".dlg_response")
	dialog "${DIALOG_GLOBALS[@]}" "$@" 2> $RESULT_FILE
	RESULT_CODE=$?
	[[ $RESULT_CODE -ne 0 ]] && return 1;
	return 0;
}
_gen.dlg --no-tags --no-items --menu "Gxbase Settings" 0 0 0 "GxBase Configuration" "Shell Configuration" "Window Manager Configuration"






















































































































































