#!/bin/bash - 
#===============================================================================
#
#          FILE: gxbase.sh
# 
#         USAGE: ./gxbase.sh 
# 
#   DESCRIPTION: 
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Gabriel Thomas Sharp (gts), osirisgothra@hotmail.com
#  ORGANIZATION: Paradisim Enterprises, LLC - http://paradisim.twilightparadox.com
#       CREATED: 11/26/2014 07:31
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error


