#!/bin/bash  -e "Do not execute directly!"
#
# GXBASE:RES:bashrc
#
# intended to be linked to your home directory as ~/.bashrc
# DO NOT copy it :) keep it in the gxbase directory where it is, 
# this is how gxbase configures itself! See the first few lines below!
#
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples
# 

while [[ ${-//[^i]} ]]; do {
	
	[[ -r ~/.hushlogin ]] && [[ "$1" != "--hush" ]] && { "$BASH_SOURCE" "--hush" "$@" &> /dev/null; return $?; }

	# gxbase placement assessment
	GXBASE_ROOT=$(dirname `dirname $(readlink -e $BASH_SOURCE)`)

	# DISABLED WHILE IN ALPHA
	#if [[ -r ${GXBASE_ROOT}/.gxbrc ]]; then
	#	GXBASE_UUID=STR_PLACEHOLDER
	#fi
	#if [[ $GXBASE_UUID != a19b9402-e2e6-11e3-bd4a-00196605e97c ]]; then
	#	echo "GXBASE UUID mismatch, cannot continue, aborting."
	#	break
	#fi

	# load gxbase
  GXBASE_LOADING=TRUE
	

	


  unset GXBASE_LOADING

	# message of the day while loading
	# but login shells do this already, so not if in a login shell
	# note that hushlogin will silence all output, so no need to do anything here
	if [[ ${0: 0:1} != "-" ]]; then
		# only if it exists
		[[ -r /etc/motd ]] && cat /etc/motd
	fi

	# inclusions 
	#    the order is very important (temp is for alpha releases only)
	source ${GXBASE_ROOT}/res/temp
	source ${GXBASE_ROOT}/res/bash-helpers
	source ${GXBASE_ROOT}/res/bash-vars
	source ${GXBASE_ROOT}/res/bash-settings
	source ${GXBASE_ROOT}/res/bash-prompt
	source ${GXBASE_ROOT}/res/bash-aliases
	source ${GXBASE_ROOT}/res/bash-traps

	# home-based additional source files
	for i in ~/.bash-*; do source "$i"; done

	# detect session type
	# - uses DISPLAY to determine if access can be given to the X session

	case ${DISPLAY:-none} in
		none)
			echo "Terminal Session Detected"
			;;
		\:[0-9]*)
			echo "Checking for X Session..."
			(xh 127.0.0.1) && {

				echo "X Session Detected"
				xh 127.0.0.1

				# these are examples of extra hosts you could have added to the access list:
				# add your own hosts here that you want connections allowed to
				xh 192.168.2.103
				xh 192.168.2.105
				xh 192.168.2.106
				xh 192.168.2.102
			}
			;;
		*)
			echo "Unknown Session Type: DISPLAY=${DISPLAY}"
			;;
	esac

	# addbashcmd() loader
	#  - processes commands added by the addbashcmd alias adding command (bash-helpers)
	for i in /home/${USERNAME}/.config/bash/*; do	
		source "$i" &> /dev/null
	done

  # font checker
	# - when default font exists, load it
	if [[ -r /usr/share/consolefonts/default.psf || -r /usr/share/consolefonts/default.psf.gz ]]; then
		# setfont only works by default if there is a "default.psf" in the consolefont directory
		setfont
	fi


	# PATH checker
	# prevents:
	# - duplicate paths
	# - missing paths in PATH
	# - actual additions to path now done in bash-vars
	unset oIFS
	[[ ! -z "$IFS" ]] && oIFS="$IFS"
	IFS=":"	
 	for i in $PATH; do
 		if [[ -d $i ]]; then
			if (echo "$NEWPATH" | grep -qP "(:|^)$i(:|$)"); then
				echo "Warning: duplicate path ignored: $i"
			else
	 			if [[ $NEWPATH ]]; then
					NEWPATH+=":$i"
				else
					NEWPATH+="$i"
				fi
			fi
		fi
	done
	PATH=$NEWPATH
	unset NEWPATH
	[[ ! -z "$oIFS" ]] && IFS=$oIFS
	break
  # always load history last
	history -n                

} done
