#!/bin/bash -c "echo \"don't execute directly!\""
#
# bash-aliases
#
#

if [[ -z $GXBASE_RES_BASHALIASES ]]; then
       GXBASE_RES_BASHALIASES+=DEFINED

	# note: do not export GXBASE_RES_BASHALIASES because aliases do not export!


  # aliases unconditional

	alias vim='vim_func -n'
	alias ls='function _lstmp() { unset -f $0; echo "$LS_HEAD"; ls --color=auto "$@"; ERR=$?; echo "$LS_TAIL"; return $ERR; }; _lstmp'
	alias grep='grep --color=auto'
	alias fgrep='fgrep --color=auto'
	alias egrep='egrep --color=auto'
	alias ll='ls -alF'
	alias la='ls -A'
	alias l='ls -CF'
	alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
	alias dir='lsfunc -batchHs --color=always'
	alias ls='lsfunc2'
	alias grep='grep --color'
	alias du='du --max-depth=1 -h'
	alias df='df -h'
	alias eb='vim -n -c ":so $GXBASE_ROOT/res/editbashes"'
	alias rls='source ~/.bashrc 1> /tmp/bash-stdoutput-last'
	alias rgx='source /etc/bash_completion; source ${GXBASE_ROOT}/startgxbase'

	# conditional aliases (and overrides to unconditionals)

	case "$(tty)" in
	
		*dev*pt*)

			# ttys @ /dev/pts/XX or /dev/ptyXX

			alias nano=mousepad
			alias vim='vim_func -'$( [[ $DISPLAY ]] && echo "g" || echo "n" )' '
			;;

		*dev*tty[0-9]*)

			# ttys @ /dev/ttyXX

			alias startdwm='startx dwm'
			alias startkde='startx startkde'
			alias startlxde='startx startlxde'
			alias xterm='startx xterm -c "xterm -fullscreen"'
			alias st='startx st'
			alias firefox='startx firefox'
			alias chrome='startx chromium-browser'
			alias pcsx='startx pcsx'
			alias zsnes='startx zsnes'
			alias gvim='startx /usr/bin/gvim_target'
			alias gimp='startx gimp'
			alias blender='startx blender'
			alias modo='startx modo'
			alias vlc='startx vlc'
			alias firefoxp='startx firefox --private-window'
			;;

		*)	
		
			# nonstandard (like when executed over a non-tty, usually when processes capture)

			;;

	esac

else
logger "aliases already defined from $BASH_SOURCE"
fi
