#!/bin/bash

DLG="dialog --backtitle \"GXBase Template Making Utility\""

function form() { 
	unset LITEMS HT TXT 
	BT=$1																																													;shift
	TXT=$																																													;shift 
	HT=$[ $# * 2 ]
	declare -i COUNT=$#
	COUNT+=1 
	for ((i=1;i<$COUNT;i++)); do 
		LITEMS+=" $1 $[ (i-1) * 2 + 1 ] 0 specify-a-value $[ (i-1) * 2 + 2 ] 1 50 50 " a
		shift
	done
	REPLY="$(dialog --stdout --backtitle $BT --form $TXT 0 0 $HT $LITEMS)"
	return $? 
}
d
