#!/bin/bash -c 'no running, must source!'

# run everything in sources.d that ends in .sh

# basic sanitation of arguments passed (strips harmful <, >,;,etc shell exploitation chars from it)
set -- `echo ${@/[<>\|;\(\*\~\!\?\$]/}`

shopt -s nullglob
for item in ${BASH_CONFIG_DIRS[root]}/sources.d/*.sh; do
	source "$item" "$@"
done

shopt -u nullglob
