#!/bin/bash
#
# gxbase-setup
#   
#   setup/configuration program for gxbase
# 
# Author:
#    Gabriel Thomas Sharp <osirisgothra@hotmail.com>  
# 
# Copyright (C)2013 Paradisim Enterprises, LLC 
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# This file was created 
# For more support, visit our homepage: http://paradisim.tk
# Report any bugs to <bugs@paradisim.tk> or visit our FAQ on our website.
#

# main menu
function mainmenu()
{
	while (true); do
		RESPONSE=$(dialog --menu "GXBASE Setup/Configuration" 0 0 0 "Setup" "Run Setup Wizard" "Main" "Set Main Options" "Variables" "Configure Environment Variables" "Alias" "Configure Shell Aliases" "Func" "Configure Environment Functions" "Light" "Configure Light Functions" "Bindings" "Configure Keyboard Bindings" "Term" "Set Terminal-Specific Options" "Paths" "Configure Program Paths" "Misc" "Configure Miscellaneous" "Exit" "Save Configuration & Exit" --cancel-label "Cancel Setup (Discard Changes)" --ok-label "Execute Selection")
		if [[ $? -gt 0 ]]; then
			break;
		else
			case ${RESPONSE^^} in
				EXIT) 
					if (dialog --keep-window --yesno "Save Changes and Exit? (No will return you to the main menu)" 0 0); then
						return 0;
					fi
					;;
				SETUP)
					;;
				*)
				 	dialog --keep-window --infotext
					true ;;
			esac                                  
		fi
	done
	return 1                                                  :
}

####### ENTRY POINT ######################################
if (mainmenu); then
	#TODO: change configuration here
	clear
	echo -e "Updating configuration..."
	true placeholder
else
	#TODO: no changes need made


























