#!/bin/bash

echo "Outside function"
function Inside()
{
	echo "Inside Function"
}
function InsideLow()
{
	echo "Execute Inside...(InsideLow is current)"
	Inside $*
	echo "Done in Inside (InsideLow i c)"
}
function InsideBottom()
{
	echo "InsideBottom, going up..."
	InsideLow
	echo "InsideBottom, going up and skipping a step..."
	Inside
	echo "InsideBottom, going down..."
}
echo "After function declaration"
echo "Going in..."
InsideBottom
echo "...Came Out"

echo "DONE"


